name: CI

on:
  pull_request_target:
    branches:
      - main
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request_target.merged == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        echo Hello, world!
        echo ${{ github.base_ref }}
        echo ${{ github.head_ref }} 
