name: CI

on:
  pull-request:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        echo Hello, world!
        echo ${{CHANGE_BRANCH}}
        echo ${{CHANGE_TARGET}}
