name: CI

on:
  pull_request:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        echo Hello, world!
        echo ${{ github.event.pull_request.base.ref }}
        echo ${{github.ref}} 
